global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'transactions-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['transactions-api:80']
        labels:
          service: 'transactions-api'

  - job_name: 'reporting-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['reporting-api:80']
        labels:
          service: 'reporting-api'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

